### PR TITLE
futures can react to shutdown

### LINKED ISSUE #268: The Raft.Shutdown() API can end up in a deadlock
I've noticed that occasionally some unit tests of [dqlite](https://github.com/CanonicalLtd/dqlite) hang forever.

I **believe** that the reason is a potential deadlock between Raft.Shutdown() and the Raft.runSnapshots() goroutine. The timeline of events looks roughly like:

1. The user calls Raft.Shutdown().Error()
2. Roughly at the same time runSnapshots() decides that it's time to kick Raft.takeSnapshot()
3. The Raft.takeSnapshot() method manages to run a bit and then block on [configReq.Error()](https://github.com/hashicorp/raft/blob/master/snapshot.go#L155) call. This can happen if the shutdown signal is being dispatched to the shutdownCh but it's not quite done, and also the call to ```r.configurationsCh <- configReq``` at line 151 succeeded (because configurationsCh is buffered with size 8), but the future was not actually processed by the main raft goroutine (either runLeader, runCandidate or runFollower)
3. The main goroutine of Raft (either runLeader, runCandidate or runFollower) receives the shutdown signal and exits **without** actually processing the pending request in configurationsCh, hence leaving takeSnapshot blocked.
4. The Error() method of future returned by Raft.Shutdown() is blocked waiting for all raft goroutines to finish, but runSnapshots will never return because it's blocked on takeSnapshot() which is in turn blocked on configReq.Error().

Hope this makes sense.

To see an example of a unit test that failed as above, look [here](https://travis-ci.org/CanonicalLtd/dqlite/builds/331818891#L539).

I'm pasting the relevant Go traceback below as well for reference.

### PR DESCRIPTION
**Pull request by i0rek**
This is implementing a very similar thing to https://github.com/hashicorp/raft/pull/277 but a little bit more generalized, like suggested by @mkeeler.

Fixes #277, fixes #268.

### CODE REVIEW

File: snapshot.go [hunk 1]
```diff
@@ -146,6 +146,7 @@ func (r *Raft) takeSnapshot() (string, error) {
 	// We have to use the future here to safely get this information since
 	// it is owned by the main thread.
 	configReq := &configurationsFuture{}
+	configReq.ShutdownCh = r.shutdownCh
```
Comment (notnoop) [inline snapshot.go]: It may be nice to document when `ShutdownCh` needs to be set and what makes snapshotting special.  I assume it's because snapshotting runs in an internal gorotouine and can run regardless of leadership.  Other futures will be responded to immediately when not leader, or when raft loses leadership as a result of shutting down?

File: future.go [hunk 2]
```diff
@@ -84,9 +84,10 @@ func (e errorFuture) Index() uint64 {
 // deferError can be embedded to allow a future
 // to provide an error in the future.
 type deferError struct {
-	err       error
-	errCh     chan error
-	responded bool
+	err        error
+	errCh      chan error
+	responded  bool
+	ShutdownCh chan struct{}
```
Comment (notnoop) [inline future.go]: very nit picky - can this field be private like the rest?
